
import { TranslationStrings, ExamTopic } from './types';

export const TRANSLATIONS: Record<'en' | 'hi', TranslationStrings> = {
  en: {
    home: 'Home',
    syllabus: 'Syllabus',
    practice: 'Practice',
    tests: 'Tests',
    profile: 'Profile',
    searchPlaceholder: 'Search topics, videos, PDFs...',
    examCountdown: 'Exam Countdown',
    daysRemaining: 'Days Left',
    quickLinks: 'Quick Links',
    studyMaterial: 'Study Material',
    pyqs: 'Previous Year Papers',
    dailyQuiz: 'Daily Quiz',
    welcomeBack: 'Welcome Back, Aspirant!',
    basicInstructor: 'Basic Instructor',
    seniorInstructor: 'Senior Instructor',
    resumeLearning: 'Resume: Data Structures',
    notifications: 'Notifications',
    aiTutor: 'Gemini AI Tutor',
    aiTutorDesc: 'Clear your computer science doubts instantly.',
    askAi: 'Ask Question',
    focusTimer: 'Focus Timer',
    start: 'Start',
    pause: 'Pause',
    reset: 'Reset',
    totalStudyTime: 'Total Study Time',
  },
  hi: {
    home: 'होम',
    syllabus: 'सिलेबस',
    practice: 'प्रैक्टिस',
    tests: 'टेस्ट',
    profile: 'प्रोफाइल',
    searchPlaceholder: 'टॉपिक, वीडियो, PDF खोजें...',
    examCountdown: 'परीक्षा उलटी गिनती',
    daysRemaining: 'दिन शेष',
    quickLinks: 'क्विक लिंक्स',
    studyMaterial: 'अध्ययन सामग्री',
    pyqs: 'पिछले वर्ष के पेपर',
    dailyQuiz: 'दैनिक क्विज़',
    welcomeBack: 'वापसी पर स्वागत है!',
    basicInstructor: 'बेसिक इंस्ट्रक्टर',
    seniorInstructor: 'सीनियर इंस्ट्रक्टर',
    resumeLearning: 'जारी रखें: डेटा स्ट्रक्चर',
    notifications: 'सूचनाएं',
    aiTutor: 'Gemini AI ट्यूटर',
    aiTutorDesc: 'कंप्यूटर विज्ञान की शंकाओं को तुरंत दूर करें।',
    askAi: 'सवाल पूछें',
    focusTimer: 'फोकस टाइमर',
    start: 'शुरू करें',
    pause: 'रोकें',
    reset: 'रीसेट',
    totalStudyTime: 'कुल अध्ययन समय',
  },
};

export const SYLLABUS_DATA: ExamTopic[] = [
  {
    id: '1',
    title: 'Computer Fundamentals',
    titleHi: 'कंप्यूटर के मूल सिद्धांत',
    progress: 85,
    subTopics: ['Generations of Computers', 'Number System', 'Memory Units', 'OS Basics'],
  },
  {
    id: '2',
    title: 'Data Structures & Algorithms',
    titleHi: 'डेटा स्ट्रक्चर और एल्गोरिथम',
    progress: 40,
    subTopics: ['Arrays', 'Linked Lists', 'Stacks', 'Queues', 'Searching & Sorting'],
  },
  {
    id: '3',
    title: 'Object Oriented Programming',
    titleHi: 'ऑब्जेक्ट ओरिएंटेड प्रोग्रामिंग',
    progress: 10,
    subTopics: ['Classes & Objects', 'Inheritance', 'Polymorphism', 'C++', 'Java Basics'],
  },
  {
    id: '4',
    title: 'Network Security',
    titleHi: 'नेटवर्क सुरक्षा',
    progress: 0,
    subTopics: ['Cryptography', 'Firewalls', 'Malware Types', 'OSI Layers'],
  }
];
